# See https://github.com/pascalgn/autoapply/blob/master/docs/deploy-keys.md
apiVersion: v1
kind: Secret
metadata:
  name: autoapply-ssh-secret
type: Opaque
data:
  id_rsa: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ...
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056Y...
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoapply
spec:
  template:
    metadata:
      labels:
        app: autoapply
    spec:
      containers:
        - name: autoapply
          image: pascalgn/autoapply:kubectl
          args: ['env:AUTOAPPLY_CONFIG']
          envFrom:
            - secretRef:
                name: autoapply-ssh-secret
          env:
            - name: AUTOAPPLY_CONFIG
              value: |
                init:
                  # Docker mounts directories as root, so this is a workaround to have SSH keys
                  # in ~/.ssh with the correct restrictive permissions (only readable by user)
                  commands:
                    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
                    - echo "${id_rsa}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
                    - echo "${known_hosts}" > ~/.ssh/known_hosts
                loop:
                  sleep: 30
                  commands:
                    - git clone --depth 1 git@github.com:pascalgn/hello-world workspace/
                    - kubectl apply -f workspace/
                server:
                  enabled: true
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
