apiVersion: v1
kind: Secret
metadata:
  name: autoapply-crypt-secret
type: Opaque
data:
  # replace with your own secret key!
  CRYPT_KEY: bXktc2VjcmV0LWtleQ==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoapply
spec:
  template:
    metadata:
      labels:
        app: autoapply
    spec:
      containers:
        - name: autoapply-container
          image: pascalgn/autoapply
          env:
            - name: URL
              value: 'https://raw.githubusercontent.com/pascalgn/hostinfo/master/examples/kubernetes.yaml'
          envFrom:
            - secretRef:
              name: autoapply-crypt-secret
