apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoapply
spec:
  template:
    metadata:
      labels:
        app: autoapply
    spec:
      containers:
        - name: autoapply
          image: pascalgn/autoapply:kubectl
          args: ["env:AUTOAPPLY_CONFIG"]
          env:
            - name: AUTOAPPLY_CONFIG
              value: |
                loop:
                  commands:
                    - git clone --depth 1 https://github.com/pascalgn/hostinfo
                    - kubectl apply -f hostinfo/examples/kubernetes.yaml
