apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoapply
spec:
  template:
    metadata:
      labels:
        app: autoapply
    spec:
      containers:
        - name: autoapply-container
          image: pascalgn/autoapply
          env:
            - name: URL
              value: 'https://raw.githubusercontent.com/pascalgn/hostinfo/master/examples/kubernetes.yaml'
            - name: KUBECONFIG
              value: /root/.kubeconfig/config
          volumeMounts:
            - name: kubeconfig-secret-volume
              mountPath: /root/.kubeconfig
      volumes:
        - name: kubeconfig-secret-volume
          secret:
            secretName: kubeconfig-secret
